title: Git and Visual Studio Startup Guide
author: Lance Moore

github_username:  lcmoore # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate
